"""empty message

Revision ID: 3c3204fd9d56
Revises: ae9d24f7ff17
Create Date: 2021-10-08 02:50:24.220726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3204fd9d56'
down_revision = 'ae9d24f7ff17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_letter', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('news_letter', 'newsletter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_letter', sa.Column('newsletter', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('news_letter', 'description')
    # ### end Alembic commands ###
